### PR TITLE
Add OWASP Frankfurt Stammtisch #49 Info

### PR DESCRIPTION
**Pull request by dansecops**
Add OWASP Frankfurt Stammtisch #49 Info

Please review, approve and merge @bkimminich @drwetter @wurstbrot

### CODE REVIEW

**Review by wurstbrot — APPROVED** [review]

**Comment by drwetter** [comment]
From my side I cannot give an approval because Rory's slides are company branded ones.

**Comment by drwetter** [comment]
I would advice going back to him, asking to remove the aqua logo e.g. on all slides except the first.

**Review by bkimminich — CHANGES_REQUESTED** [review]
Remove vendor logos from anything but "Hi, I am ... and work for ..." slide.

**Comment by dansecops** [comment]
@bkimminich @drwetter Agreed, branded slides are against the speaker agreement, thanks for pointing this out. Hence, I have removed Rory's slides from the upload until I have received non-branded slides. 

Please check again the changes and provide your approval unless there is anything else.

**Pull request merged**
