### PR TITLE
add online stammtisch 

### PR DESCRIPTION
**Pull request by wurstbrot**

### CODE REVIEW

**Comment by JanWolff** [comment]
Other options mentioned were: cyber4edu and senfcall .

**Comment by wurstbrot** [comment]
I understood that the other options are maybe not good to mention public.

**Comment by JanWolff** [comment]
I understood that https://senfcall.de/ could be mentioned and that they were rather forthcoming.

**Comment by bkimminich** [comment]
I've fixed a few issues via 71f8fd0 ... 😉

**Comment by JanWolff** [comment]
Good point. It took me a while to spot the issue. :-)

**Pull request merged**
