### PR TITLE
Updated contact and frequency, added a topic

### PR DESCRIPTION
**Pull request by Laxarella**
Updated contact and frequency, added a topic

### CODE REVIEW

**Comment by Laxarella** [comment]
Leipzig: Updated contact and frequency, added a topic

**Comment by wurstbrot** [comment]
@Laxarella there are conflicts, can you resolve them?

**Comment by bkimminich** [comment]
Also it would be great if you could use your owasp.org emails for contact info. If you don't have one yet, please contact OWASP staff via Atlassian form to get one. Thanks!

**Comment by bkimminich** [comment]
I'm closing this PR due to unresolved conflicts. Please rebase your local clone and open a new PR as needed, @Laxarella.

**Pull request closed without merging**
